"""Se añade la confirmación de usuarios

Revision ID: 29614f181972
Revises: 8b807cbb88d8
Create Date: 2023-05-03 13:33:15.939385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29614f181972'
down_revision = '8b807cbb88d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
